# Generated by Django 2.0.7 on 2018-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivagation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road_construction',
            name='rwe_closure_type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
