# Generated by Django 2.0.3 on 2018-08-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivagation', '0002_road_construction_rwe_closure_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='road_construction',
            table='road',
        ),
    ]
